//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCrypt.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCrypt.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easily encrypt files and folders with a high secured AES encryption system well integrated in Windows Explorer.
        ///
        ///- LICENSE -
        ///This application is a creation of Matthieu Badoy, who owns the author rights. Pleasy do NOT modify this application. You are allowed to share this application, by putting a link to this license.
        ///
        ///Thanks to Metro UI for the spinning loader.
        ///-----------.
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A file named.
        /// </summary>
        internal static string AFileNamed {
            get {
                return ResourceManager.GetString("AFileNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à already exists. Do you want to replace it?.
        /// </summary>
        internal static string alreadyExistsReplaceIt {
            get {
                return ResourceManager.GetString("alreadyExistsReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during file decryption..
        /// </summary>
        internal static string AnErrorOccuredDuringDecryption {
            get {
                return ResourceManager.GetString("AnErrorOccuredDuringDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during file encryption..
        /// </summary>
        internal static string AnErrorOccuredDuringEncryption {
            get {
                return ResourceManager.GetString("AnErrorOccuredDuringEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author:.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking password.
        /// </summary>
        internal static string CheckingPassword {
            get {
                return ResourceManager.GetString("CheckingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a file to open.
        /// </summary>
        internal static string ChooseFileToOpen {
            get {
                return ResourceManager.GetString("ChooseFileToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a folder to encrypt.
        /// </summary>
        internal static string ChooseFolderToEncrypt {
            get {
                return ResourceManager.GetString("ChooseFolderToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose save location.
        /// </summary>
        internal static string ChooseSaveLocation {
            get {
                return ResourceManager.GetString("ChooseSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compressing data.
        /// </summary>
        internal static string CompressingData {
            get {
                return ResourceManager.GetString("CompressingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompressing data.
        /// </summary>
        internal static string DecompressingData {
            get {
                return ResourceManager.GetString("DecompressingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrypt.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrypting.
        /// </summary>
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decryption successful!.
        /// </summary>
        internal static string DecryptionSuccessful {
            get {
                return ResourceManager.GetString("DecryptionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details:.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypting.
        /// </summary>
        internal static string Encrypting {
            get {
                return ResourceManager.GetString("Encrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypting back the.
        /// </summary>
        internal static string EncryptingBackThe {
            get {
                return ResourceManager.GetString("EncryptingBackThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypting the.
        /// </summary>
        internal static string EncryptingThe {
            get {
                return ResourceManager.GetString("EncryptingThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption successful!.
        /// </summary>
        internal static string EncryptionSuccessful {
            get {
                return ResourceManager.GetString("EncryptionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à file.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finalizing.
        /// </summary>
        internal static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à folder.
        /// </summary>
        internal static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It is impossible to decrypt a directory..
        /// </summary>
        internal static string ImpossibleToDecryptDirectory {
            get {
                return ResourceManager.GetString("ImpossibleToDecryptDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MCrypt is hard working: exiting the application could result in a loss of data.
        ///Do you REALLY want to exit?.
        /// </summary>
        internal static string MCryptHardWorkingPrompt {
            get {
                return ResourceManager.GetString("MCryptHardWorkingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opening.
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original file has been moved or deleted before decryption..
        /// </summary>
        internal static string OriginalFileMovedBeforeDecryption {
            get {
                return ResourceManager.GetString("OriginalFileMovedBeforeDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original object to encrypt has been moved or deleted before encryption..
        /// </summary>
        internal static string OriginalObjectToEnryptMoved {
            get {
                return ResourceManager.GetString("OriginalObjectToEnryptMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entered passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please confirm the password..
        /// </summary>
        internal static string PleaseConfirmPassword {
            get {
                return ResourceManager.GetString("PleaseConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a password..
        /// </summary>
        internal static string PleaseEnterAPassword {
            get {
                return ResourceManager.GetString("PleaseEnterAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your password..
        /// </summary>
        internal static string PleaseEnterYourPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please drop only one file..
        /// </summary>
        internal static string PleaseOnlyDropOneFile {
            get {
                return ResourceManager.GetString("PleaseOnlyDropOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a file to open..
        /// </summary>
        internal static string PleaseSelectFile {
            get {
                return ResourceManager.GetString("PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please specify the location of the output file..
        /// </summary>
        internal static string PleaseSpecifyOutputLocation {
            get {
                return ResourceManager.GetString("PleaseSpecifyOutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing.
        /// </summary>
        internal static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing decryption.
        /// </summary>
        internal static string PreparingDecryption {
            get {
                return ResourceManager.GetString("PreparingDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing encryption.
        /// </summary>
        internal static string PreparingEncryption {
            get {
                return ResourceManager.GetString("PreparingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading metadata.
        /// </summary>
        internal static string ReadingMetadata {
            get {
                return ResourceManager.GetString("ReadingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified directory does not exist..
        /// </summary>
        internal static string SpecifiedDirectoryDoesntExist {
            get {
                return ResourceManager.GetString("SpecifiedDirectoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified object does not exists..
        /// </summary>
        internal static string SpecifiedObjectNotFound {
            get {
                return ResourceManager.GetString("SpecifiedObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à step.
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file to decrypt is not a MCrypt encrypted file..
        /// </summary>
        internal static string TheFileToDecryptIsNotMCryptFile {
            get {
                return ResourceManager.GetString("TheFileToDecryptIsNotMCryptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for the file to exit.
        /// </summary>
        internal static string WaitingForTheFileToExit {
            get {
                return ResourceManager.GetString("WaitingForTheFileToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Writing metadata.
        /// </summary>
        internal static string WritingMetadata {
            get {
                return ResourceManager.GetString("WritingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong password.
        ///
        ///(Note: a lost password is unrecoverable).
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
